### YamlMime:ManagedReference
items:
- uid: ADLXWrapper.Adlx3DSettings
  commentId: T:ADLXWrapper.Adlx3DSettings
  id: Adlx3DSettings
  parent: ADLXWrapper
  children:
  - ADLXWrapper.Adlx3DSettings.ApplyProfile(ADLXWrapper.ThreeDSettingsProfile)
  - ADLXWrapper.Adlx3DSettings.Dispose
  - ADLXWrapper.Adlx3DSettings.Finalize
  - ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle
  - ADLXWrapper.Adlx3DSettings.GetProfile
  langs:
  - csharp
  - vb
  name: Adlx3DSettings
  nameWithType: Adlx3DSettings
  fullName: ADLXWrapper.Adlx3DSettings
  type: Class
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: Adlx3DSettings
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 8
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  summary: Facade for 3D settings services bound to a GPU.
  example: []
  syntax:
    content: 'public sealed class Adlx3DSettings : IDisposable'
    content.vb: Public NotInheritable Class Adlx3DSettings Implements IDisposable
  inheritance:
  - System.Object
  implements:
  - System.IDisposable
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ADLXWrapper.Adlx3DSettings.GetProfile
  commentId: M:ADLXWrapper.Adlx3DSettings.GetProfile
  id: GetProfile
  parent: ADLXWrapper.Adlx3DSettings
  langs:
  - csharp
  - vb
  name: GetProfile()
  nameWithType: Adlx3DSettings.GetProfile()
  fullName: ADLXWrapper.Adlx3DSettings.GetProfile()
  type: Method
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: GetProfile
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 24
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  syntax:
    content: public ThreeDSettingsProfile GetProfile()
    return:
      type: ADLXWrapper.ThreeDSettingsProfile
    content.vb: Public Function GetProfile() As ThreeDSettingsProfile
  overload: ADLXWrapper.Adlx3DSettings.GetProfile*
- uid: ADLXWrapper.Adlx3DSettings.ApplyProfile(ADLXWrapper.ThreeDSettingsProfile)
  commentId: M:ADLXWrapper.Adlx3DSettings.ApplyProfile(ADLXWrapper.ThreeDSettingsProfile)
  id: ApplyProfile(ADLXWrapper.ThreeDSettingsProfile)
  parent: ADLXWrapper.Adlx3DSettings
  langs:
  - csharp
  - vb
  name: ApplyProfile(ThreeDSettingsProfile)
  nameWithType: Adlx3DSettings.ApplyProfile(ThreeDSettingsProfile)
  fullName: ADLXWrapper.Adlx3DSettings.ApplyProfile(ADLXWrapper.ThreeDSettingsProfile)
  type: Method
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: ApplyProfile
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 30
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  syntax:
    content: public void ApplyProfile(ThreeDSettingsProfile profile)
    parameters:
    - id: profile
      type: ADLXWrapper.ThreeDSettingsProfile
    content.vb: Public Sub ApplyProfile(profile As ThreeDSettingsProfile)
  overload: ADLXWrapper.Adlx3DSettings.ApplyProfile*
- uid: ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle
  commentId: M:ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle
  id: Get3DSettingsServicesHandle
  parent: ADLXWrapper.Adlx3DSettings
  langs:
  - csharp
  - vb
  name: Get3DSettingsServicesHandle()
  nameWithType: Adlx3DSettings.Get3DSettingsServicesHandle()
  fullName: ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle()
  type: Method
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: Get3DSettingsServicesHandle
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 37
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  syntax:
    content: public AdlxInterfaceHandle Get3DSettingsServicesHandle()
    return:
      type: ADLXWrapper.AdlxInterfaceHandle
    content.vb: Public Function Get3DSettingsServicesHandle() As AdlxInterfaceHandle
  overload: ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle*
- uid: ADLXWrapper.Adlx3DSettings.Dispose
  commentId: M:ADLXWrapper.Adlx3DSettings.Dispose
  id: Dispose
  parent: ADLXWrapper.Adlx3DSettings
  langs:
  - csharp
  - vb
  name: Dispose()
  nameWithType: Adlx3DSettings.Dispose()
  fullName: ADLXWrapper.Adlx3DSettings.Dispose()
  type: Method
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: Dispose
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 44
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  summary: Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
  example: []
  syntax:
    content: public void Dispose()
    content.vb: Public Sub Dispose()
  overload: ADLXWrapper.Adlx3DSettings.Dispose*
  implements:
  - System.IDisposable.Dispose
- uid: ADLXWrapper.Adlx3DSettings.Finalize
  commentId: M:ADLXWrapper.Adlx3DSettings.Finalize
  id: Finalize
  parent: ADLXWrapper.Adlx3DSettings
  langs:
  - csharp
  - vb
  name: ~Adlx3DSettings()
  nameWithType: Adlx3DSettings.~Adlx3DSettings()
  fullName: ADLXWrapper.Adlx3DSettings.~Adlx3DSettings()
  type: Method
  source:
    remote:
      path: ADLXWrapper/Adlx3DSettings.cs
      branch: feature-api-overhaul
      repo: https://github.com/terrymacdonald/ADLXWrapper.git
    id: Finalize
    path: ADLXWrapper/Adlx3DSettings.cs
    startLine: 60
  assemblies:
  - ADLXWrapper
  namespace: ADLXWrapper
  syntax:
    content: protected ~Adlx3DSettings()
    content.vb: 'Protected '
  overload: ADLXWrapper.Adlx3DSettings.Finalize*
  nameWithType.vb: ''
  fullName.vb: ''
  name.vb: ''
references:
- uid: ADLXWrapper
  commentId: N:ADLXWrapper
  href: ADLXWrapper.html
  name: ADLXWrapper
  nameWithType: ADLXWrapper
  fullName: ADLXWrapper
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ADLXWrapper.Adlx3DSettings.GetProfile*
  commentId: Overload:ADLXWrapper.Adlx3DSettings.GetProfile
  href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_GetProfile
  name: GetProfile
  nameWithType: Adlx3DSettings.GetProfile
  fullName: ADLXWrapper.Adlx3DSettings.GetProfile
- uid: ADLXWrapper.ThreeDSettingsProfile
  commentId: T:ADLXWrapper.ThreeDSettingsProfile
  parent: ADLXWrapper
  href: ADLXWrapper.ThreeDSettingsProfile.html
  name: ThreeDSettingsProfile
  nameWithType: ThreeDSettingsProfile
  fullName: ADLXWrapper.ThreeDSettingsProfile
- uid: ADLXWrapper.Adlx3DSettings.ApplyProfile*
  commentId: Overload:ADLXWrapper.Adlx3DSettings.ApplyProfile
  href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_ApplyProfile_ADLXWrapper_ThreeDSettingsProfile_
  name: ApplyProfile
  nameWithType: Adlx3DSettings.ApplyProfile
  fullName: ADLXWrapper.Adlx3DSettings.ApplyProfile
- uid: ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle*
  commentId: Overload:ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle
  href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_Get3DSettingsServicesHandle
  name: Get3DSettingsServicesHandle
  nameWithType: Adlx3DSettings.Get3DSettingsServicesHandle
  fullName: ADLXWrapper.Adlx3DSettings.Get3DSettingsServicesHandle
- uid: ADLXWrapper.AdlxInterfaceHandle
  commentId: T:ADLXWrapper.AdlxInterfaceHandle
  parent: ADLXWrapper
  href: ADLXWrapper.AdlxInterfaceHandle.html
  name: AdlxInterfaceHandle
  nameWithType: AdlxInterfaceHandle
  fullName: ADLXWrapper.AdlxInterfaceHandle
- uid: ADLXWrapper.Adlx3DSettings.Dispose*
  commentId: Overload:ADLXWrapper.Adlx3DSettings.Dispose
  href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_Dispose
  name: Dispose
  nameWithType: Adlx3DSettings.Dispose
  fullName: ADLXWrapper.Adlx3DSettings.Dispose
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: ADLXWrapper.Adlx3DSettings.Finalize*
  commentId: Overload:ADLXWrapper.Adlx3DSettings.Finalize
  href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_Finalize
  name: ~Adlx3DSettings
  nameWithType: Adlx3DSettings.~Adlx3DSettings
  fullName: ADLXWrapper.Adlx3DSettings.~Adlx3DSettings
  spec.csharp:
  - name: "~"
  - uid: ADLXWrapper.Adlx3DSettings.Finalize*
    name: Adlx3DSettings
    href: ADLXWrapper.Adlx3DSettings.html#ADLXWrapper_Adlx3DSettings_Finalize
